### ISSUE TITLE
How to install it

### ISSUE THREAD

**Issue by MaxBubblegum47** [AlexBSoft/win95.css#5]
I'm quite new to Django and web developing but I'd Like to use your theme for my university project. How can I setup it? I'm using Pycharm and by now I'm only able to display the "index.html" page but the theme is the bootstrap one :(

**Comment by AlexBSoft** [comment]
I am not familiar with Django. 
Just install Bootstrap 4 as usual and then include theme css. It is simple.

Something like this:

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://raw.githubusercontent.com/AlexBSoft/win95.css/master/assets/win95.css">
```
